;;; Automatically generated by ‘recentf’ on Thu Oct  7 22:27:31 2021.

(setq recentf-list
      '(
        "/home/eemil/.emacs.d/init.el"
        "/home/eemil/dev/clai/src/vm.c"
        "/home/eemil/dev/clai/test.lai"
        "/home/eemil/dev/clai/src/compiler.c"
        "/home/eemil/dev/yeaah/yeaah3.cpp"
        "/home/eemil/dev/yeaah/yeaah2.cpp"
        "/home/eemil/dev/asmlai/src/codegen_x64.cpp"
        "/home/eemil/dev/asmlai/src/parser.cpp"
        "/home/eemil/dev/asmlai/test.lai"
        "/home/eemil/dev/asmlai/src/compiler.cpp"
        "/home/eemil/dev/yeaah/alue50"
        "/home/eemil/dev/yeaah/yeaah.cpp"
        "/home/eemil/dev/yeaah/input"
        "/home/eemil/dev/asmlai/out.s"
        "/home/eemil/dev/asmlai/src/compiler.h"
        "/home/eemil/dev/asmlai/src/ast.h"
        "/home/eemil/dev/yeaah/yeaah.py"
        "/home/eemil/dev/asmlai/src/lexer.cpp"
        "/home/eemil/dev/asmlai/src/lexer.h"
        "/home/eemil/dev/asmlai/src/parser.h"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
