;;; Automatically generated by ‘recentf’ on Thu Oct 14 22:21:51 2021.

(setq recentf-list
      '(
        "/home/eemil/.emacs.d/init.el"
        "/home/eemil/go/src/github.com/nireo/goshop/client/src/App.tsx"
        "/home/eemil/go/src/github.com/nireo/goshop/client/src/index.tsx"
        "/home/eemil/go/src/github.com/nireo/goshop/client/src/components/Navbar.tsx"
        "/home/eemil/go/src/github.com/nireo/goshop/server/database/sqlc/item_test.go"
        "/usr/lib/go/src/strconv/itoa.go"
        "/home/eemil/go/src/github.com/nireo/goshop/server/database/sqlc/item.sql.go"
        "/home/eemil/go/src/github.com/nireo/goshop/server/database/sqlc/user_test.go"
        "/home/eemil/dev/asmlai/src/codegen_x64.cpp"
        "/home/eemil/dev/asmlai/src/lexer.cpp"
        "/usr/include/string.h"
        "/home/eemil/dev/asmlai/src/token.h"
        "/home/eemil/dev/asmlai/src/lexer.h"
        "/home/eemil/dev/asmlai/src/parser.cpp"
        "/home/eemil/dev/yeaah/yeaah4.cpp"
        "/home/eemil/dev/yeaah/input"
        "/home/eemil/.Xresources"
        "/home/eemil/dev/yeaah/yeaah5.py"
        "/home/eemil/dev/asmlai/src/ast.h"
        "/home/eemil/dev/asmlai/src/parser.h"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
