;;; Automatically generated by ‘recentf’ on Fri Sep 24 18:36:54 2021.

(setq recentf-list
      '(
        "/home/eemil/dev/asmlai/src/parser.cpp"
        "/home/eemil/dev/asmlai/src/codegen_x64.cpp"
        "/home/eemil/dev/asmlai/src/compiler.h"
        "/home/eemil/.emacs.d/init.el"
        "/home/eemil/dev/asmlai/test.lai"
        "/home/eemil/dev/asmlai/src/compiler.cpp"
        "/home/eemil/dev/asmlai/out.s"
        "/home/eemil/dev/asmlai/xddd/main.c"
        "/home/eemil/dev/asmlai/src/main.cpp"
        "/home/eemil/dev/asmlai/src/ast.h"
        "/home/eemil/dev/asmlai/src/codegen_x64.h"
        "/home/eemil/dev/asmlai/xddd/compiler.h"
        "/home/eemil/dev/asmlai/README.md"
        "/home/eemil/dev/clai/src/main.c"
        "/home/eemil/dev/clai/src/vm.c"
        "/home/eemil/dev/clai/src/vm.h"
        "/home/eemil/dev/asmlai/src/token.h"
        "/home/eemil/dev/asmlai/src/parser.h"
        "/home/eemil/dev/clai/src/table.h"
        "/home/eemil/dev/clai/src/object.c"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
